apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: itl-terranetes-controller
  namespace: argocd
  labels:
    app.kubernetes.io/name: itl-terranetes-controller
    app.kubernetes.io/part-of: terraform-platform
    app.kubernetes.io/component: infrastructure-controller
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/ITlusions/ITL.Terranetes.git
    targetRevision: main
    path: chart
    helm:
      values: |
        itl:
          enabled: true
          organization:
            name: "ITlusions"
            domain: "itlusions.com"
          environment:
            name: "production"
            region: "westeurope"
          
          keycloak:
            enabled: true
            server:
              enabled: true
              url: "https://sts.itlusions.com"
              adminRealm: "master"
              adminCredentials:
                secretName: "keycloak-admin-credentials"
                usernameKey: "username"
                passwordKey: "password"
            realm:
              name: "ITL-Academy"
              displayName: "ITL Academy"
              enabled: true
            clientId: "terranetes"
            
          monitoring:
            enabled: true
            namespace: "monitoring"
            
          backup:
            enabled: true
            schedule: "0 2 * * *"
            retentionDays: 30

        terranetes-controller:
          enabled: true
          
          controller:
            costs:
              enabled: true
              secret: "infracost-api"
              
            policy:
              enabled: true
              source: "https://github.com/itlusions/terraform-policies"
              
          replicaCount: 2
          
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: terraform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    # Ignore Terranetes controller webhook configuration drift
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: terranetes-controller-manager-webhook
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /metadata/resourceVersion
        - /metadata/generation
        - /metadata/annotations
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: terranetes-controller-manager-webhook
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /metadata/resourceVersion
        - /metadata/generation
        - /metadata/annotations
    # Ignore auto-assigned cluster IPs and service drift
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
        - /metadata/resourceVersion
        - /status
    # Ignore secrets that may be managed externally
    - group: ""
      kind: Secret
      name: terranetes-controller-manager-webhook-certs
      jsonPointers:
        - /data
        - /metadata/resourceVersion
    # Ignore CRD status and metadata drift
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /status
        - /metadata/resourceVersion
        - /metadata/generation
        - /metadata/annotations/kubectl.kubernetes.io/last-applied-configuration
    # Ignore deployment status and conditions
    - group: apps
      kind: Deployment
      jsonPointers:
        - /status
        - /metadata/resourceVersion
        - /metadata/generation
    # Ignore pod disruption budget status
    - group: policy
      kind: PodDisruptionBudget
      jsonPointers:
        - /status
        - /metadata/resourceVersion
    # Ignore ConfigMap drift for dynamic configurations
    - group: ""
      kind: ConfigMap
      name: terranetes-controller-manager-config
      jsonPointers:
        - /metadata/resourceVersion
    # Ignore ServiceAccount token annotations
    - group: ""
      kind: ServiceAccount
      jsonPointers:
        - /metadata/annotations/kubectl.kubernetes.io/last-applied-configuration
        - /metadata/resourceVersion
        - /secrets
  revisionHistoryLimit: 10
  info:
    - name: 'Description'
      value: 'ITL Terranetes Controller for Infrastructure as Code with Terraform and OpenTofu'
    - name: 'Documentation'
      value: 'https://terranetes.appvia.io/'
    - name: 'Repository'
      value: 'https://github.com/ITlusions/ITL.Terranetes'
    - name: 'Maintainer'
      value: 'ITL Academy DevOps Team'