{{- if and .Values.itl.keycloak.enabled .Values.itl.keycloak.clients }}
{{- range $client := .Values.itl.keycloak.clients }}
{{- if $client.enabled }}
---
apiVersion: terraform.appvia.io/v1alpha1
kind: Configuration
metadata:
  name: {{ $client.name }}
  namespace: {{ $.Values.global.namespace | default "terraform-system" }}
  labels:
    {{- include "itl-terranetes.labels" $ | nindent 4 }}
    itl.academy/component: keycloak-client
    itl.academy/client-name: {{ $client.name | quote }}
    itl.academy/client-id: {{ $client.clientId | quote }}
spec:
  module: git::https://github.com/ITlusions/ITL.Terranetes.Modules.git//keycloak/client?ref=v1.0.0
  
  providerRef:
    name: keycloak
    namespace: {{ $.Values.global.namespace | default "terraform-system" }}
  
  {{- if $.Values.itl.keycloak.realm.name }}
  dependsOn:
    - name: {{ $.Values.itl.keycloak.realm.name | lower }}-realm
  {{- end }}
  
  variables:
    # Required variables
    realm_id: {{ $.Values.itl.keycloak.realm.name | default "ITL-Academy" | quote }}
    client_id: {{ $client.clientId | quote }}
    name: {{ $client.name | quote }}
    
    # Access configuration
    {{- if $client.publicClient }}
    access_type: "PUBLIC"
    {{- else }}
    access_type: "CONFIDENTIAL"
    {{- end }}
    
    {{- if $client.redirectUris }}
    valid_redirect_uris:
      {{- toYaml $client.redirectUris | nindent 6 }}
    {{- end }}
    
    {{- if $client.webOrigins }}
    web_origins:
      {{- toYaml $client.webOrigins | nindent 6 }}
    {{- end }}
    
    {{- if $client.baseUrl }}
    base_url: {{ $client.baseUrl | quote }}
    {{- end }}
    
    {{- if $client.adminUrl }}
    admin_url: {{ $client.adminUrl | quote }}
    {{- end }}
    
    # Flow configuration
    standard_flow_enabled: {{ $client.standardFlowEnabled | default true }}
    implicit_flow_enabled: {{ $client.implicitFlowEnabled | default false }}
    direct_access_grants_enabled: {{ $client.directAccessGrantsEnabled | default false }}
    service_accounts_enabled: {{ $client.serviceAccountsEnabled | default false }}
    
    {{- if $client.publicClient }}
    pkce_code_challenge_method: "S256"
    {{- end }}
    
    # Security settings
    full_scope_allowed: false
    
    {{- if $client.roles }}
    create_roles:
      {{- range $client.roles }}
      - name: {{ . | quote }}
        description: {{ printf "%s role for %s" . $client.name | quote }}
      {{- end }}
    {{- end }}
    
    # Default scopes for ITL Academy
    default_client_scopes:
      - "profile"
      - "email"
      - "roles"
    
    # ITL standard tags
    itl_tags:
      "itl.academy/environment": {{ $.Values.itl.environment.name | default "production" | quote }}
      "itl.academy/organization": {{ $.Values.itl.organization.name | default "ITlusions" | quote }}
      "itl.academy/managed-by": "terranetes"
      "itl.academy/component": "keycloak-client"
      "itl.academy/client": {{ $client.clientId | quote }}
      "itl.academy/protocol": {{ $client.protocol | default "openid-connect" | quote }}

  writeConnectionSecretsToRef:
    name: {{ $client.name }}-outputs
    namespace: {{ $.Values.global.namespace | default "terraform-system" }}

{{- end }}
{{- end }}
{{- end }}