{{- if and .Values.itl.keycloak.enabled .Values.itl.keycloak.realm.enabled }}
---
apiVersion: terraform.appvia.io/v1alpha1
kind: Configuration
metadata:
  name: {{ .Values.itl.keycloak.realm.name | lower }}-realm
  namespace: {{ .Values.global.namespace | default "terraform-system" }}
  labels:
    {{- include "itl-terranetes.labels" . | nindent 4 }}
    itl.academy/component: keycloak-realm
    itl.academy/realm: {{ .Values.itl.keycloak.realm.name | quote }}
spec:
  module: git::https://github.com/ITlusions/ITL.Terranetes.Modules.git//keycloak/realm?ref=main
  
  providerRef:
    name: keycloak
    namespace: {{ .Values.global.namespace | default "terraform-system" }}
  
  variables:
    # Basic realm configuration
    realm_name: {{ .Values.itl.keycloak.realm.name | quote }}
    display_name: {{ .Values.itl.keycloak.realm.displayName | quote }}
    enabled: {{ .Values.itl.keycloak.realm.enabled }}
    
    # User registration and management
    {{- with .Values.itl.keycloak.realm.settings }}
    registration_allowed: {{ .registrationAllowed | default false }}
    registration_email_as_username: {{ .registrationEmailAsUsername | default true }}
    remember_me: {{ .rememberMe | default true }}
    verify_email: {{ .verifyEmail | default true }}
    reset_password_allowed: {{ .resetPasswordAllowed | default true }}
    
    # Session configuration
    sso_session_idle_timeout: {{ .ssoSessionIdleTimeout | default 1800 }}
    sso_session_max_lifespan: {{ .ssoSessionMaxLifespan | default 36000 }}
    
    # Security settings
    brute_force_protected: {{ .bruteForceProtected | default true }}
    failure_factor: {{ .failureFactor | default 5 }}
    wait_increment_seconds: {{ .waitIncrementSeconds | default 60 }}
    quick_login_check_milli_seconds: {{ .quickLoginCheckMilliSeconds | default 1000 }}
    {{- end }}
    
    # ITL-specific realm attributes
    realm_attributes:
      "itl.academy/organization": {{ .Values.itl.organization.name | default "ITlusions" | quote }}
      "itl.academy/environment": {{ .Values.itl.environment.name | default "production" | quote }}
      "itl.academy/domain": {{ .Values.itl.organization.domain | default "itlusions.com" | quote }}
    
    # Default roles for the realm
    default_roles:
      - "student"
      - "instructor"
      - "admin"
    
    {{- if .Values.itl.keycloak.groups }}
    # User groups
    groups:
      {{- range .Values.itl.keycloak.groups }}
      - name: {{ .name | quote }}
        display_name: {{ .displayName | quote }}
        description: {{ .description | quote }}
        {{- if .realmRoles }}
        realm_roles:
          {{- toYaml .realmRoles | nindent 10 }}
        {{- end }}
      {{- end }}
    {{- end }}
    
    # ITL standard tags
    itl_tags:
      "itl.academy/environment": {{ .Values.itl.environment.name | default "production" | quote }}
      "itl.academy/organization": {{ .Values.itl.organization.name | default "ITlusions" | quote }}
      "itl.academy/managed-by": "terranetes"
      "itl.academy/component": "keycloak-realm"
      "itl.academy/realm": {{ .Values.itl.keycloak.realm.name | quote }}

  writeConnectionSecretsToRef:
    name: {{ .Values.itl.keycloak.realm.name | lower }}-realm-outputs
    namespace: {{ .Values.global.namespace | default "terraform-system" }}

{{- end }}