{{- if .Values.monitoring.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "itl-terranetes.fullname" . }}
  namespace: {{ .Values.global.namespace | default "terraform-system" }}
  labels:
    {{- include "itl-terranetes.labels" . | nindent 4 }}
    {{- include "itl-terranetes.itlLabels" . | nindent 4 }}
    {{- if .Values.monitoring.prometheus.serviceMonitor.labels }}
    {{- toYaml .Values.monitoring.prometheus.serviceMonitor.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "itl-terranetes.itlAnnotations" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: terranetes-controller
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
    honorLabels: true
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'terranetes_.*'
      action: keep
    - sourceLabels: [namespace]
      targetLabel: itl_namespace
    - sourceLabels: [configuration]
      targetLabel: itl_configuration
    - replacement: "ITL Academy"
      targetLabel: organization
    - replacement: {{ .Values.itl.environment.name | quote }}
      targetLabel: environment
---
{{- end }}
{{- if .Values.monitoring.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "itl-terranetes.fullname" . }}-grafana-dashboard
  namespace: {{ .Values.monitoring.grafana.namespace | default "monitoring" }}
  labels:
    {{- include "itl-terranetes.labels" . | nindent 4 }}
    {{- include "itl-terranetes.itlLabels" . | nindent 4 }}
    grafana_dashboard: "1"
  annotations:
    {{- include "itl-terranetes.itlAnnotations" . | nindent 4 }}
data:
  terranetes-overview.json: |
    {
      "dashboard": {
        "id": null,
        "title": "ITL Terranetes Controller - Overview",
        "tags": ["terranetes", "itl", "infrastructure"],
        "style": "dark",
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Active Configurations",
            "type": "stat",
            "targets": [
              {
                "expr": "sum(terranetes_configuration_total{organization=\"ITL Academy\"})",
                "legendFormat": "Total Configurations"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "color": {"mode": "palette-classic"},
                "custom": {"displayMode": "basic"},
                "unit": "short"
              }
            },
            "options": {
              "reduceOptions": {
                "values": false,
                "calcs": ["lastNotNull"],
                "fields": ""
              },
              "orientation": "auto",
              "textMode": "auto",
              "colorMode": "value",
              "graphMode": "area",
              "justifyMode": "auto"
            },
            "gridPos": {"h": 8, "w": 6, "x": 0, "y": 0}
          },
          {
            "id": 2,
            "title": "Success Rate",
            "type": "stat",
            "targets": [
              {
                "expr": "sum(rate(terranetes_configuration_success_total{organization=\"ITL Academy\"}[5m])) / sum(rate(terranetes_configuration_total{organization=\"ITL Academy\"}[5m])) * 100",
                "legendFormat": "Success Rate %"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "color": {"mode": "thresholds"},
                "custom": {"displayMode": "basic"},
                "unit": "percent",
                "thresholds": {
                  "steps": [
                    {"color": "red", "value": 0},
                    {"color": "yellow", "value": 80},
                    {"color": "green", "value": 95}
                  ]
                }
              }
            },
            "gridPos": {"h": 8, "w": 6, "x": 6, "y": 0}
          },
          {
            "id": 3,
            "title": "Policy Compliance",
            "type": "stat",
            "targets": [
              {
                "expr": "sum(terranetes_policy_passed_total{organization=\"ITL Academy\"}) / sum(terranetes_policy_total{organization=\"ITL Academy\"}) * 100",
                "legendFormat": "Compliance %"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "color": {"mode": "thresholds"},
                "unit": "percent",
                "thresholds": {
                  "steps": [
                    {"color": "red", "value": 0},
                    {"color": "yellow", "value": 90},
                    {"color": "green", "value": 98}
                  ]
                }
              }
            },
            "gridPos": {"h": 8, "w": 6, "x": 12, "y": 0}
          },
          {
            "id": 4,
            "title": "Monthly Cost Trend",
            "type": "timeseries",
            "targets": [
              {
                "expr": "sum(terranetes_cost_estimate{organization=\"ITL Academy\"}) by (environment)",
                "legendFormat": "{{ "{{environment}}" }}"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "color": {"mode": "palette-classic"},
                "custom": {
                  "drawStyle": "line",
                  "lineInterpolation": "linear",
                  "pointSize": 5,
                  "fillOpacity": 20
                },
                "unit": "currencyUSD"
              }
            },
            "gridPos": {"h": 8, "w": 6, "x": 18, "y": 0}
          },
          {
            "id": 5,
            "title": "Configuration Status by Environment",
            "type": "piechart",
            "targets": [
              {
                "expr": "sum(terranetes_configuration_total{organization=\"ITL Academy\"}) by (status, environment)",
                "legendFormat": "{{ "{{environment}} - {{status}}" }}"
              }
            ],
            "options": {
              "reduceOptions": {
                "values": false,
                "calcs": ["lastNotNull"],
                "fields": ""
              },
              "pieType": "pie",
              "tooltip": {"mode": "single", "sort": "none"},
              "legend": {
                "displayMode": "visible",
                "placement": "right"
              }
            },
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 8}
          },
          {
            "id": 6,
            "title": "Drift Detection Results",
            "type": "table",
            "targets": [
              {
                "expr": "terranetes_drift_detected{organization=\"ITL Academy\"}",
                "legendFormat": "",
                "format": "table"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "custom": {
                  "align": "auto",
                  "displayMode": "auto"
                }
              }
            },
            "options": {
              "showHeader": true
            },
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 8}
          }
        ],
        "time": {
          "from": "now-24h",
          "to": "now"
        },
        "refresh": "5m",
        "schemaVersion": 27,
        "version": 1
      }
    }
{{- end }}